name: Validate Documentation

on:
  pull_request:
    branches:
      - master
    paths:
      - 'packages/docs/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      working-directory: ./packages/docs
    - run: npm run build --if-present
      working-directory: ./packages/docs
    - run: npm run test --if-present
      working-directory: ./packages/docs
    - run: npm run lint
      working-directory: ./packages/docs
      env:
        CI: true
