name: Validate Documentation

on:
  pull_request:
    branches:
      - master
    paths:
      - 'packages/docs/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
      working-directory: ./packages/docs
    - name: Build the package
      run: npm run build
      working-directory: ./packages/docs
    - name: Run the tests
      run: npm run test --if-present
      working-directory: ./packages/docs
    - name: Run the linter
      run: npm run lint
      working-directory: ./packages/docs
      env:
        CI: true
